// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const SCHEMA_NAME = 'sacadaohboy-mrkitsch-loungerie';

// Create client with global headers to ensure Accept-Profile is always sent
// IMPORTANT: 
// - Accept-Profile: Used for SELECT queries (reading data)
// - Content-Profile: Used for INSERT/UPDATE/DELETE (writing data)
// We need BOTH headers to ensure all operations use the correct schema
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    headers: {
      'Accept-Profile': SCHEMA_NAME,  // For SELECT queries
      'Content-Profile': SCHEMA_NAME, // For INSERT/UPDATE/DELETE queries
    },
  },
});
