// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const SCHEMA_NAME = 'sistemaretiradas';

// Create client with schema configured in db.schema option
// This is CRITICAL: without this, supabase-js defaults to 'public' schema
// Even with Accept-Profile headers, we need db.schema to ensure all queries use the correct schema
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  db: {
    schema: SCHEMA_NAME,  // ← THIS IS THE KEY! Forces all queries to use sistemaretiradas schema
  },
  global: {
    headers: {
      'Accept-Profile': SCHEMA_NAME,  // For SELECT queries (PostgREST)
      'Content-Profile': SCHEMA_NAME, // For INSERT/UPDATE/DELETE queries (PostgREST)
    },
  },
});
